"""initial

Revision ID: 06d0ae9a23fc
Revises:
Create Date: 2026-06-30 02:49:19.117346

"""

from collections.abc import Sequence

import sqlalchemy as sa

import google_news.models._types  # noqa: F401 — needed for StringArray in column defs
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "06d0ae9a23fc"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "articles",
        sa.Column(
            "article_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("publisher_domain", sa.Text(), nullable=False),
        sa.Column("headline", sa.Text(), nullable=False),
        sa.Column("snippet", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("language", sa.Text(), nullable=False),
        sa.Column("region", sa.Text(), nullable=False),
        sa.Column("source_authority", sa.Float(), nullable=False),
        sa.Column("story_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("article_id"),
        sa.UniqueConstraint("url", name="uq_articles_url"),
    )
    op.create_index(op.f("ix_articles_published_at"), "articles", ["published_at"], unique=False)
    op.create_index(
        op.f("ix_articles_publisher_domain"), "articles", ["publisher_domain"], unique=False
    )
    op.create_index(op.f("ix_articles_story_id"), "articles", ["story_id"], unique=False)

    # PostgreSQL FTS index — conditional; SQLite skips it.
    if op.get_bind().dialect.name == "postgresql":
        op.create_index(
            "ix_articles_fts",
            "articles",
            [sa.text("to_tsvector('english', headline || ' ' || coalesce(snippet, ''))")],
            postgresql_using="gin",
        )

    op.create_table(
        "stories",
        sa.Column(
            "story_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("canonical_headline", sa.Text(), nullable=False),
        sa.Column("article_count", sa.Integer(), nullable=False),
        sa.Column("top_sources", google_news.models._types.StringArray(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("first_published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("story_id"),
    )
    op.create_table(
        "user_events",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "event_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("article_id", sa.UUID(), nullable=False),
        sa.Column("story_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id", "event_id"),
    )
    op.create_index(op.f("ix_user_events_article_id"), "user_events", ["article_id"], unique=False)
    op.create_index(op.f("ix_user_events_story_id"), "user_events", ["story_id"], unique=False)
    op.create_table(
        "user_profiles",
        sa.Column(
            "user_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("followed_topics", google_news.models._types.StringArray(), nullable=False),
        sa.Column("followed_sources", google_news.models._types.StringArray(), nullable=False),
        sa.Column("region", sa.Text(), nullable=False),
        sa.Column("language_prefs", google_news.models._types.StringArray(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        op.drop_index("ix_articles_fts", table_name="articles", postgresql_using="gin")
    op.drop_table("user_profiles")
    op.drop_index(op.f("ix_user_events_story_id"), table_name="user_events")
    op.drop_index(op.f("ix_user_events_article_id"), table_name="user_events")
    op.drop_table("user_events")
    op.drop_table("stories")
    op.drop_index(op.f("ix_articles_story_id"), table_name="articles")
    op.drop_index(op.f("ix_articles_publisher_domain"), table_name="articles")
    op.drop_index(op.f("ix_articles_published_at"), table_name="articles")
    op.drop_table("articles")
    # ### end Alembic commands ###
